AllCops:
  Exclude:
    - '**/Dangerfile'
    - '**/Brewfile'
    - '**/Gemfile'
    - '**/Podfile'
    - '**/Rakefile'
    - '**/Fastfile'
    - '**/Deliverfile'
    - '**/*.gemspec'

Metrics/BlockLength:
  Enabled: false